## Hydra configuration for training pipeline

# ============================================================
# file: conf/train/train_config.yaml
# ============================================================
# Top‑level Hydra config (defaults)
defaults:
  - data: default
  - trainer: multi      # sklearn | multi | lstm
  - strategy: mean        # none | mean | median | weighted
  - _self_

# Global MLflow & experiment metadata
tracking_uri: "http://127.0.0.1:5000"
registry_uri: "http://127.0.0.1:5000"
experiment: "investment_analysis_demo_5"
model_tag: "combiner_mean"

# Validation settings (used by TrainModelManager)
validation:
  method: holdout          # holdout only for now (manager handles)
  val_size_days: 60

